<?php //if($this->pages): ?>
<!--<ul class="breadcrumb">-->
<!--    --><?php //foreach ($this->pages as $key => $page): ?>
<!--        <li>-->
<!--            --><?php //if ($key < count($this->pages) - 1): ?>
<!--                <a href="--><?php //echo $page->getHref(); ?><!--">--><?php //echo $page->getLabel(); ?><!--</a>-->
<!--            --><?php //else: ?>
<!--                --><?php //echo $page->getLabel(); ?>
<!--            --><?php //endif; ?>
<!--        </li>-->
<!--    --><?php //endforeach; ?>
<!--</ul>-->
<?php //endif; ?>
<!--<!-- Wrapper-->
<!--<div id="wrapper">-->
<!---->
<!--    <!-- Navigation -->
<!--    <div ng-include="'navigation.html'"></div>-->
<!---->
<!--    <!-- Page wraper -->
<!--    <!-- ng-class with current state name give you the ability to extended customization your view -->
<!--    <div id="page-wrapper" class="gray-bg {{$state.current.name}}">-->
<!---->
<!--        <!-- Page wrapper -->
<!--        <div ng-include="topnavbar.html"></div>-->
<!---->
<!--        <!-- Main view  -->
<!--        <div ui-view></div>-->
<!---->
<!--        <!-- Footer -->-->
<!--        <div ng-include="footer.html"></div>-->
<!---->
<!--    </div>-->
<!--    <!-- End page wrapper-->
<!---->
<!--    <!-- Right Sidebar -->
<!--    <div ng-include="right_sidebar.html"></div>-->


<!--<!-- End wrapper-->
<!--<nav class="navbar-default navbar-static-side" role="navigation">-->
<!--    <div class="sidebar-collapse">-->
<!--        <ul side-navigation class="nav" id="side-menu">-->
<!--            <li class="nav-header">-->
<!---->
<!--                <div class="dropdown profile-element" dropdown>-->
<!--                    <img alt="image" class="img-circle" src="../img/profile_small.jpg"/>-->
<!--                    <a class="dropdown-toggle" dropdown-toggle href>-->
<!--                            <span class="clear">-->
<!--                                <span class="block m-t-xs">-->
<!--                                    <strong class="font-bold">Frezer Tadesse</strong>-->
<!--                             </span>-->
<!--                                <span class="text-muted text-xs block">country Admin<b class="caret"></b></span>-->
<!--                            </span>-->
<!--                    </a>-->
<!--                    <ul class="dropdown-menu animated fadeInRight m-t-xs">-->
<!--                          <li><a ui-sref="profile">Profile</a></li>-->
<!--                          <li><a ui-sref="contacts">Contacts</a></li>-->
<!--                          <li><a ui-sref="inbox">Mailbox</a></li>-->
<!--                          <li class="divider"></li>-->
<!--                        <li><a href="--><?php //echo $this->url('zfcuser/logout'); ?><!--">Logout</a></li>-->
<!--                    </ul>-->
<!--                </div>-->
<!--                <div class="logo-element">-->
<!--                    //  IN+-->
<!--                </div>-->
<!--            </li>-->
<!--            <li ng-class="{active: $state.includes('dashboards')}">-->
<!--                <a href="index.html"><i class="fa fa-th-large"></i> <span class="nav-label">{{ 'DASHBOARD'  }}</span> <span class="fa arrow"></span></a>-->
<!--                <ul class="nav nav-second-level" ng-class="{in: $state.includes('dashboards')}">-->
<!--                    <li ui-sref-active="active"><a ui-sref="dashboards.dashboard_1">{{ 'DASHBOARD'  }}</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="dashboards.dashboard_2">{{ 'Register'   }} </a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="dashboards.dashboard_3">{{ 'Login'   }}</a></li>-->
<!--                    <!--  <li ui-sref-active="active"><a ui-sref="dashboards.dashboard_4_1">{{ 'DASHBOARD' | translate }} v.4</a></li> -->-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li ng-class="{active: $state.includes('tables')}">-->
<!--                <a href=""><i class="fa fa-table"></i> <span class="nav-label">{{ 'Desciples'  }}</span><span class="fa arrow"></span></a>-->
<!--                <ul class="nav nav-second-level" ng-class="{in: $state.includes('tables')}">-->
<!--                    <li ui-sref-active="active"><a ui-sref="tables.static_table">Add</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="tables.data_tables">List</a></li>-->
<!--                    <!--     <li ui-sref-active="active"><a ui-sref="tables.nggrid">NG Grid</a></li> -->-->
<!--                </ul>-->
<!--            </li>-->
<!---->
<!---->
<!---->

<!--            </li>-->
<!--            <li ui-sref-active="active">-->
<!--                <a ui-sref="layouts"><i class="fa fa-certificate"></i> <span class="nav-label">{{ 'WIN'   }}</span> <span class="label label-primary pull-right">12</span></a>-->
<!--            </li>-->
<!--            <!---->
<!--                        <li ng-class="{active: $state.includes('charts')}">-->
<!--                            <a href=""><i class="fa fa-bar-chart-o"></i> <span class="nav-label">{{ 'GRAPHS' | translate }}</span><span class="fa arrow"></span></a>-->
<!--                            <ul class="nav nav-second-level" ng-class="{in: $state.includes('charts')}">-->
<!--                                <li ui-sref-active="active"><a ui-sref="charts.flot_chart">Flot Charts</a></li>-->
<!--                                <li ui-sref-active="active"><a ui-sref="charts.rickshaw_chart">Rickshaw Charts</a></li>-->
<!--                                <li ui-sref-active="active"><a ui-sref="charts.chartjs_chart">Chart.js</a></li>-->
<!--                                <li ui-sref-active="active"><a ui-sref="charts.peity_chart">Peity Charts</a></li>-->
<!--                                <li ui-sref-active="active"><a ui-sref="charts.sparkline_chart">Sparkline Charts</a></li>-->
<!--                            </ul>-->
<!--                        </li>-->
<!--                        <li ng-class="{active: $state.includes('mailbox')}">-->
<!--                            <a ui-sref="inbox"><i class="fa fa-envelope"></i> <span class="nav-label">{{ 'MAILBOX' | translate }} </span><span class="label label-warning pull-right">16/24</span></a>-->
<!--                            <ul class="nav nav-second-level" ng-class="{in: $state.includes('mailbox')}">-->
<!--                                <li ui-sref-active="active"><a ui-sref="mailbox.inbox">Inbox</a></li>-->
<!--                                <li ui-sref-active="active"><a ui-sref="mailbox.email_view">Email view</a></li>-->
<!--                                <li ui-sref-active="active"><a ui-sref="mailbox.email_compose">Compose email</a></li>-->
<!--                                <li ui-sref-active="active"><a ui-sref="mailbox.email_template">Email template</a></li>-->
<!--                            </ul>-->
<!--                        </li>-->
<!--            -->-->
<!--            <li ui-sref-active="active">-->
<!--                <a ui-sref="widgets"><i class="fa fa-eye"></i> <span class="nav-label">{{ 'BUILD'   }}</span><span class="label label-primary pull-right">25</span></a>-->
<!--            </li>-->
<!---->
<!---->
<!--            <li ui-sref-active="active">-->
<!--                <a ui-sref="grid_options"><i class="fa fa-send"></i> <span class="nav-label">{{ 'SEND'   }}</span><span class="label label-primary pull-right">10</span></a>-->
<!--            </li>-->
<!--            <!---->
<!---->
<!--            <li ng-class="{active: $state.includes('forms')}">-->
<!--<-->
<!--                <a href=""><i class="fa fa-edit"></i> <span class="nav-label">{{ 'WBS' | translate }}</span><span class="fa arrow"></span></a>-->
<!--                <ul class="nav nav-second-level" ng-class="{in: $state.includes('forms')}">-->
<!--                    <li ui-sref-active="active"><a ui-sref="forms.basic_form">Win</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="forms.advanced_plugins">Advanced Plugins</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="forms.wizard.step_one">Build</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="forms.file_upload">Send</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="forms.text_editor">Text Editor</a></li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <!---->
<!--                      <li ng-class="{active: $state.includes('app')}">-->
<!--                          <a href=""><i class="fa fa-desktop"></i> <span class="nav-label">{{ 'APPVIEWS' | translate }}</span>  <span class="pull-right label label-primary">SPECIAL</span></a>-->
<!--                          <ul class="nav nav-second-level" ng-class="{in: $state.includes('app')}">-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.contacts">Contacts</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.profile">Profile</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.projects">Projects</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.project_detail">Project detail</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.teams_board">Teams board</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.clients">Clients</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.file_manager">File manager</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.calendar">Calendar</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.issue_tracker">Issue tracker</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.blog">Blog</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.article">Article</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.faq">FAQ</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.timeline">Timeline</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.pin_board">Pin board</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="app.invoice">Invoice</a></li>-->
<!--                          </ul>-->
<!--                      </li>-->
<!--                      <li ng-class="{active: $state.includes('pages')}">-->
<!--                          <a href=""><i class="fa fa-files-o"></i> <span class="nav-label">{{ 'OTHERPAGES' | translate }}</span><span class="fa arrow"></span></a>-->
<!--                          <ul class="nav nav-second-level" ng-class="{in: $state.includes('pages')}">-->
<!--                              <li ui-sref-active="active"><a ui-sref="pages.search_results">Search results</a></li>-->
<!--                              <li><a href="lockscreen.html">Lockscreen</a></li>-->
<!--                              <li><a href="404.html">404 Page</a></li>-->
<!--                              <li><a href="500.html">500 Page</a></li>-->
<!--                              <li><a href="login.html">Login</a></li>-->
<!--                              <li><a href="login_two_columns.html">Login v.2</a></li>-->
<!--                              <li><a href="forgot_password.html">Forget password</a></li>-->
<!--                              <li><a href="register.html">Register</a></li>-->
<!--                              <li ui-sref-active="active"><a ui-sref="pages.empy_page">Empty page</a></li>-->
<!--                          </ul>-->
<!--                      </li>-->
<!--                      -->-->
<!---->
<!--            <!---->
<!--            <li ng-class="{active: $state.includes('ui')}">-->
<!--                <a href=""><i class="fa fa-flask"></i> <span class="nav-label">{{ 'UIELEMENTS' | translate }}</span><span class="fa arrow"></span></a>-->
<!--                <ul class="nav nav-second-level" ng-class="{in: $state.includes('ui')}">-->
<!--                    <li ui-sref-active="active"><a ui-sref="ui.typography">Typography</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="ui.icons">Icons</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="ui.draggable">Draggable Panels</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="ui.buttons">Buttons</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="ui.video">Video</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="ui.tabs_panels">Tabs & Panels</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="ui.notifications_tooltips">Notifications & Tooltips</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="ui.badges_labels">Badges, Labels, Progress</a></li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            -->-->
<!---->
<!--            <!---->
<!--            <li ng-class="{active: $state.includes('gallery')}">-->
<!--                <a href=""><i class="fa fa-picture-o"></i> <span class="nav-label">{{ 'GALLERY' | translate }}</span><span class="fa arrow"></span></a>-->
<!--                <ul class="nav nav-second-level" ng-class="{in: $state.includes('gallery')}">-->
<!--                    <li ui-sref-active="active"><a ui-sref="gallery.basic_gallery">Lightbox Gallery</a></li>-->
<!--                    <li ui-sref-active="active"><a ui-sref="gallery.bootstrap_carousel">Bootstrap Carusela</a></li>-->
<!---->
<!--                </ul>-->
<!--            </li>-->
<!--            ---->
<!---->
<!--            <li>-->
<!--                <a href=""><i class="fa fa-sitemap"></i> <span class="nav-label">{{ 'Desciples' | translate }}</span><span class="fa arrow"></span></a>-->
<!--                <ul class="nav nav-second-level">-->
<!---->
<!--                    <li><a href="">Add</a></li>-->
<!--                    <li><a href="">List</a></li>-->
<!---->
<!--                </ul>-->
<!--            </li>-->
<!--            -->
<!--            <li ui-sref-active="active">-->
<!--                <a ui-sref="css_animations"><i class="fa fa-tree"></i> <span class="nav-label">{{ 'Tree'}}</span><span class="label label-info pull-right"></span></a>-->
<!--            </li>-->
<!--            <!---->
<!--            <li class="landing_link">-->
<!--                <a target="_blank" href="../../Landing_page/index.html"><i class="fa fa-star"></i> <span class="nav-label">{{ 'LANDING' | translate }}</span> <span class="label label-warning pull-right">NEW</span></a>-->
<!--            </li>-->
<!--            <li class="special_link">-->
<!--                <a href="../index.html"><i class="fa fa-html5"></i> <span class="nav-label">HTML/CSS Version</span></a>-->
<!--            </li>-->
<!--        </ul>-->
<!--        -->-->
</ul>
<!--    </div>-->
<!--</nav>-->