<!---->
<!--<!DOCTYPE html>-->
<!--<html ng-app="inspinia">-->
<!---->
<!--<head>-->
<!---->
<!--    <meta charset="utf-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!---->
    <!-- Page title set in pageTitle directive -->
<!--    <title page-title></title>-->
<!---->
    <!-- Font awesome -->
<!--    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">-->
<!---->
    <!-- Bootstrap -->
<!--    <link href="bootstrap.min.css" rel="stylesheet">-->
<!---->
    <!-- Main Inspinia CSS files -->
<!--    <link href="css/animate.css" rel="stylesheet">-->
<!--    <link id="loadBefore" href="css/style.css" rel="stylesheet">-->
<!---->
<!---->
<!--</head>-->
<!---->
<!-- ControllerAs syntax -->
<!-- Main controller with serveral data used in Inspinia theme on diferent view -->
<!--<body ng-controller="MainCtrl as main"></body>-->
        <!-- Scripts -->
<!---->
<!-- Main view  -->
<!--<div ui-view></div>-->
<!---->
<!-- jQuery and Bootstrap -->
<!--<script src="js/jquery/jquery-2.1.1.min.js"></script>-->
<!--<script src="js/plugins/jquery-ui/jquery-ui.js"></script>-->
<!--<script src="js/bootstrap/bootstrap.min.js"></script>-->
<!---->
<!-- MetsiMenu -->
<!--<script src="public/js/plugins/metisMenu/jquery.metisMenu.js"></script>-->
<!---->
<!-- SlimScroll -->
<!--<script src="public/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>-->
<!---->
<!-- Peace JS -->
<!--<script src="js/plugins/pace/pace.min.js"></script>-->
<!---->
<!-- Custom and plugin javascript -->
<!--<script src="js/inspinia.js"></script>-->
<!---->
<!-- Main Angular scripts-->
<!--<script src="js/angular/angular.min.js"></script>-->
<!--<script src="js/plugins/oclazyload/dist/ocLazyLoad.min.js"></script>-->
<!--<script src="js/angular-translate/angular-translate.min.js"></script>-->
<!--<script src="js/ui-router/angular-ui-router.min.js"></script>-->
<!--<script src="js/bootstrap/ui-bootstrap-tpls-0.12.0.min.js"></script>-->
<!--<script src="js/plugins/angular-idle/angular-idle.js"></script>-->
<!---->
<!--
<!-- You need to include this script on any page that has a Google Map.-->
<!-- When using Google Maps on your own site you MUST signup for your own API key at:-->
<!-- https://developers.google.com/maps/documentation/javascript/tutorial#api_key-->
<!-- After your sign up replace the key in the URL below..-->

<!--<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDQTpXj82d8UpCi97wzo_nKXL7nYrd4G70"></script>-->
<!---->
<!-- Anglar App Script -->
<script src="js/app.js"></script>
<script src="js/config.js"></script>
<script src="js/translations.js"></script>
<script src="js/directives.js"></script>
<script src="js/controllers.js"></script>
<script src="js/vendor/Gettext.js"></script>
<!---->
<!--</body>-->
<!--</html>-->
<?php //echo $this->doctype(); ?>
<!---->
<!--[if IE 9]> <html class="no-js ie ie9 lte9" lang="en" ng-app="skeleton"> <![endif]-->
<!--<html lang="--><?php //echo \Locale::getDefault(); ?><!--" ng-app="skeleton">-->
<!--<head>-->
<!--    <meta charset="utf-8">-->
<!--    --><?php //echo $this->headTitle()->prepend('deeplife')->setSeparator(' - ')->setAutoEscape(false) ?>
<!---->
<!--    --><?php //echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
<!---->
    <!-- Le styles -->
<!--    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>-->
<!--    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">-->
<!--    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">-->
<!--    <link href="//cdn.jsdelivr.net/angular.ngtable/0.3.1/ng-table.css" rel="stylesheet">-->
<!---->
<!--    <link rel="stylesheet" href="/dist/css/min.dc46.css" media="screen"/>-->
<!---->
<!--    <link href="/dist/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">-->
<!---->
    <!-- Language file for javascript translations -->
<!--    <link href="/i18n/--><?php //echo \Locale::getDefault(); ?><!--.po" rel="gettext" type="application/x-po">-->
<!---->
    <!-- Scripts -->
<!--    --><?php //echo $this->headScript(); ?>
<!--</head>-->
<!---->
<!--<body>-->
<!---->
<!--<div id="wrapper">-->
<!---->
<!--    <div id="sidebar-wrapper" class="hidden-print">-->
<!--        <a class="sidebar-brand" href="--><?php //echo $this->url('home') ?><!--"><img src="--><?php //echo $this->basePath('../img/logo/logo.png') ?><!--" alt="ZF2"/></a>-->
<!--        <div class="sidebar-nav-container">-->
<!--            --><?php //echo $this->navigation('navigation')->menu()->setUlClass('sidebar-nav'); ?>
<!--        </div>-->
<!--    </div>-->
<!---->
<!--    <div id="page-content-wrapper">-->
<!--        <div class="page-content inset">-->
<!--            <div class="row">-->
<!--                <div class="container col-md-8">-->
<!--                    <div class="top-menu hidden-print">-->
<!--                        <a data-toggle="dropdown" href="#"><i class="fa fa-gear settings"></i></a>-->
<!--                        --><?php //echo $this->navigation('secondary_navigation')->menu()->setUlClass('dropdown-menu actions'); ?>
<!--                        <p class="user">-->
<!--                           --><?php
//                            $displayName = $this->zfcUserDisplayName();
//                            if($displayName):
//                                echo $displayName;
//                                ?>
                                &nbsp;
                                <a href="<?php echo $this->url('zfcuser/logout'); ?>"><?php echo 'Logout'; ?></a>

                                <a href="<?php echo $this->url('zfcuser/login'); ?>"><?php echo 'Login'; ?></a>

<!--                        </p>-->
<!--                    </div>-->
<!---->
<!--                    <div class="hide" app-messages></div>-->
<!---->
<!--                    <div id="container" class="clearfix ">-->
<!--                        <div class="hidden-print">-->
<!--                            --><?php
//                            echo $this->navigation('navigation')
//                                ->breadcrumbs()
//                                ->setMinDepth(0)
//                                ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
//                            echo $this->navigation('secondary_navigation')
//                                ->breadcrumbs()
//                                ->setMinDepth(0)
//                                ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
////                            ?>
<!--                        </div>-->
                        <?php echo $this->content; ?>
<!--                        <footer></footer>-->
<!--                    </div>-->
<!---->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<!---->
<!-- Scripts -->
<!--<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>-->
<!--<script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>-->
<!--<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.20/angular.min.js"></script>-->
<!--<script type="text/javascript" src="//cdn.jsdelivr.net/angularjs/1.2.20/angular-resource.min.js"></script>-->
<!--<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.10.0/ui-bootstrap.min.js"></script>-->
<!--<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.10.0/ui-bootstrap-tpls.min.js"></script>-->
<!--<script type="text/javascript" src="//cdn.jsdelivr.net/angular.ngtable/0.3.3/ng-table.js"></script>-->
<!---->
<!-- <script src="js/min.336e.js"></script>-->
<!---->
<?php echo $this->inlineScript(); ?>
<!---->
<!--</body>-->
<!---->
<!--</html>-->

<!DOCTYPE html>
<html ng-app="inspinia">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Page title set in pageTitle directive -->
    <title page-title></title>

    <!-- Font awesome -->
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Main Inspinia CSS files -->
    <link href="css/animate.css" rel="stylesheet">
    <link id="loadBefore" href="css/style.css" rel="stylesheet">


</head>

<!-- ControllerAs syntax -->
<!-- Main controller with serveral data used in Inspinia theme on diferent view -->
<body ng-controller="MainCtrl as main">

<!-- Main view  -->
<div ui-view></div>

<!-- jQuery and Bootstrap -->
<script src="js/jquery/jquery-2.1.1.min.js"></script>
<script src="js/plugins/jquery-ui/jquery-ui.js"></script>
<script src="js/bootstrap/bootstrap.min.js"></script>

<!-- MetsiMenu -->
<script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>

<!-- SlimScroll -->
<script src="js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<!-- Peace JS -->
<script src="js/plugins/pace/pace.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="js/inspinia.js"></script>
</body>
<!-- Main Angular scripts-->
<script src="js/angular/angular.min.js"></script>
<script src="js/plugins/oclazyload/dist/ocLazyLoad.min.js"></script>
<script src="js/angular-translate/angular-translate.min.js"></script>
<script src="js/ui-router/angular-ui-router.min.js"></script>
<script src="js/bootstrap/ui-bootstrap-tpls-0.12.0.min.js"></script>
<script src="js/plugins/angular-idle/angular-idle.js"></script>

<!--
 You need to include this script on any page that has a Google Map.
 When using Google Maps on your own site you MUST signup for your own API key at:
 https://developers.google.com/maps/documentation/javascript/tutorial#api_key
 After your sign up replace the key in the URL below..
-->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDQTpXj82d8UpCi97wzo_nKXL7nYrd4G70"></script>

<!-- Anglar App Script -->
<script src="js/app.js"></script>
<script src="js/config.js"></script>
<script src="js/translations.js"></script>
<script src="js /directives.js"></script>
<script src="js/controllers.js"></script>
<script src="js/user.js"></script>
<script src="js/tax.js"></script>
<script src="js/role.js"></script>
<script src="js/skeleton.js"></script>
<script src="js/services/tax.js"></script>
<script src="js/services/user.js"></script>
<script src="js/services/role.js"></script>
<script src="js/services/utils.js"></script>
<script src="js/services.js"></script>

</body>
</html>
